### ISSUE TITLE
Memory access out of bounds

### ISSUE THREAD

**Issue by TJKoury** [wapm-packages/OpenSSL#1]
Trying a simple example in node using [wasi](https://github.com/wasmerio/wasmer-js/tree/master/packages/wasi):

```
import WASI from "@wasmer/wasi";
import fs from 'fs';

let wasi = new WASI({
  args: [],
  env: {},
  bindings: {
    ...WASI.defaultBindings,
    fs
  }
});

const startWasiTask = async () => {
  const wasm_bytes = fs.readFileSync('./openssl.wasm');
  let {
    instance
  } = await WebAssembly.instantiate(wasm_bytes, {
    wasi_unstable: wasi.wasiImport
  });
  wasi.start(instance);

};
startWasiTask();
```
Getting a this error:

```
 UnhandledPromiseRejectionWarning: RuntimeError: memory access out of bounds
    at opt_progname (wasm-function[158]:32)
    at main (wasm-function[146]:567)
    at _start (wasm-function[24]:405)
```

**Comment by TJKoury** [comment]
Also, tried using `lowerI64Imports` as well, same error.

**Comment by torch2424** [comment]
@TJKoury 

Hello! Thanks for opening an issue!

So  we do have OpenSSL working with [Wasmer-Js](https://github.com/wasmerio/wasmer-js): https://twitter.com/wasmerio/status/1187874502107004928

I saw you closed the issue, is this resolved? Do you have a fix that you could possibly share in case someone else runs into the same issue?

Thank you! 😄 

cc @syrusakbary

**Comment by TJKoury** [comment]
@torch2424 Sure, the answer was to just put in the actual arguments into args, a good test case might be:

```
let wasi = new WASI({
  args: ["openssl", "genrsa"],
  env: {},
  bindings: {
    ...WASI.defaultBindings
  }
});
```

I'm still having issues reading stdout, `await wasmFs.getStdOut();` does not seem to work from the  [example](https://github.com/wasmerio/wasmer-js/tree/master/packages/wasi).  Nothing will run after `wasi.start(instance);`.  The output is written to the Node.js stdout no matter what is called (or not called).

**Comment by TJKoury** [comment]
Looks like this is a known issue with wasi and node that the core team is working on.

**Comment by torch2424** [comment]
@TJKoury Thanks for all the updates here 😄 Was about to do an investiagation, but since it's a wasi / node issue, I think it is something that will need to be solved on their end?

Thanks gain for all the updates here 😄

**Comment by TJKoury** [comment]
@torch2424 No problem!  I don't think there is any action for you to take here, they will address it in node very soon.
